spring:
  application:
    name: config-server
  profiles:
    active:
    - native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
        git:
          uri: https://github.com/kornsook/chapter5.git
          searchPaths: configfiles
        vault:
          port: 8200
          host: 127.0.0.1
          kvVersion: 2
          authentication: token
          token: '{cipher}024c74fa80012546951621bb6f11cae92c931831f314b2823e13ca4788228002'
    
server:
  port: 8071
  
encrypt:
  key: fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo 


#Enable all Spring Boot Actuator endpoints.
management:
  endpoints:
    web:
      exposure:
        include: "*"