spring:
  application:
    name: config-server
  profiles:
    active:
    - native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
        git:
          uri: https://github.com/Fidac/Configuration-Assignment5
          searchPaths: configfiles
        vault:
          port: 8200
          host: 127.0.0.1
          kvVersion: 2
          authentication: token
          token: '{cipher}f875f673a44c41e021b24ec26ae302e17f1b906bc02a063b619325be5046dde9'
    
server:
  port: 8071
  
encrypt:
  key: fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo 


#Enable all Spring Boot Actuator endpoints.
management:
  endpoints:
    web:
      exposure:
        include: "*"